version: 2
jobs:
  build:
    
    working_directory: ~/jsonplaceholder

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:

      - checkout
         
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: jsonplaceholder-{{ checksum "pom.xml" }}
      
      - run: mvn clean install
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/jsonplaceholder-0.0.1-SNAPSHOT.jar

