version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Run tests
          command: mvn clean install

      - run:
          name: Print the Current Time
          command: date
